import os
import torch
import numpy as np
import pickle
import argparse
import json
import yaml

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from copy import deepcopy
from tqdm import tqdm

from utils import load_data  # data functions
from utils import compute_dict_mean, set_seed, detach_dict  # helper functions
from act_policy import ACTPolicy, CNNMLPPolicy

import IPython
e = IPython.embed

try:
    import wandb  # type: ignore
except Exception:
    wandb = None


def _wandb_enabled(config: dict) -> bool:
    """
    Enable W&B logging only when explicitly configured to avoid
    breaking training in environments without W&B credentials.
    """
    if wandb is None:
        return False
    if os.environ.get("WANDB_DISABLED", "").strip().lower() in {"1", "true", "yes"}:
        return False
    wandb_project = config.get("wandb_project")
    return bool(wandb_project)


def _init_wandb(config: dict) -> "object | None":
    if not _wandb_enabled(config):
        return None

    wandb_project = config.get("wandb_project") or "UniVTAC"
    wandb_entity = config.get("wandb_entity")
    wandb_mode = config.get("wandb_mode") or "online"
    wandb_run_name = config.get("wandb_run_name")

    try:
        init_kwargs = {
            "project": wandb_project,
            "config": config,
        }
        if wandb_entity:
            init_kwargs["entity"] = wandb_entity
        if wandb_mode:
            init_kwargs["mode"] = wandb_mode
        if wandb_run_name:
            init_kwargs["name"] = wandb_run_name

        return wandb.init(**init_kwargs)  # type: ignore[union-attr]
    except Exception as exc:
        print(f"[W&B] Failed to initialize W&B; continuing without it. Error: {exc}")
        return None


def main(args):
    set_seed(1)
    # command line parameters
    is_eval = args["eval"]
    ckpt_dir = args["ckpt_dir"]
    policy_class = args["policy_class"]
    onscreen_render = args["onscreen_render"]
    task_name = args["task_name"]
    batch_size_train = args["batch_size"]
    batch_size_val = args["batch_size"]

    # get task parameters
    is_sim = task_name[:4] == "sim-"
    if is_sim:
        # TacArena: load from JSON file generated by process_data.py
        SIM_TASK_CONFIGS_PATH = "./SIM_TASK_CONFIGS.json"
        with open(SIM_TASK_CONFIGS_PATH, "r") as f:
            SIM_TASK_CONFIGS = json.load(f)
        task_config = SIM_TASK_CONFIGS[task_name]
    else:
        from aloha_scripts.constants import TASK_CONFIGS
        task_config = TASK_CONFIGS[task_name]
    
    dataset_dir = task_config["dataset_dir"]
    num_episodes = task_config["num_episodes"]
    episode_len = task_config["episode_len"]
    camera_names = args["camera_names"]

    # fixed parameters
    if policy_class == "CNNMLP":
        policy_config = {
            "lr": args["lr"],
            "lr_backbone": args["lr_backbone"],
            "backbone": args["backbone"],
            "num_queries": 1,
            "camera_names": camera_names,
        }
    elif policy_class != "ACT":
        raise NotImplementedError

    state_dim = args["state_dim"]
    tactile_names = args["tactile_names"]
    chunk_size = args["chunk_size"]
    config = {
        "num_epochs": 6000,
        "ckpt_dir": ckpt_dir,
        "episode_len": episode_len,
        "state_dim": state_dim,
        "lr": args["lr"],
        "policy_class": policy_class,
        "onscreen_render": onscreen_render,
        "policy_config": args,
        "task_name": task_name,
        "seed": args["seed"],
        "temporal_agg": args["temporal_agg"],
        "camera_names": camera_names,
        "real_robot": not is_sim,
        "save_freq": args['save_freq'],
        "num_steps": args['num_steps'],
        # W&B (optional)
        "wandb_project": args.get("wandb_project"),
        "wandb_entity": args.get("wandb_entity"),
        "wandb_mode": args.get("wandb_mode"),
        "wandb_run_name": args.get("wandb_run_name"),
        "wandb_log_ckpts": bool(args.get("wandb_log_ckpts", False)),
    }

    # Initialize W&B after the main training config exists.
    wandb_run = _init_wandb(config)

    if is_eval:
        print("=" * 60)
        print("TacArena ACT Policy Evaluation")
        print("=" * 60)
        print("Please use the unified evaluation script:")
        print("  python scripts/eval_policy.py policy/ACT/deploy_policy_{task_name}.yml")
        print("")
        print("Note: TacArena uses IsaacLab simulation environment for evaluation.")
        print("      The eval_bc() function is for RoboTwin's MuJoCo environment.")
        print("=" * 60)
        exit()

    train_dataloader, val_dataloader, stats, _ = load_data(dataset_dir, num_episodes, camera_names, tactile_names, batch_size_train, batch_size_val, chunk_size)

    # save dataset stats
    if not os.path.isdir(ckpt_dir):
        os.makedirs(ckpt_dir)
    stats_path = os.path.join(ckpt_dir, f"dataset_stats.pkl")
    with open(stats_path, "wb") as f:
        pickle.dump(stats, f)
    best_ckpt_info = train_bc(train_dataloader, val_dataloader, config)
    best_epoch, min_val_loss, best_state_dict = best_ckpt_info

    # save best checkpoint
    ckpt_path = os.path.join(ckpt_dir, f"policy_best.ckpt")
    torch.save(best_state_dict, ckpt_path)
    print(f"Best ckpt, val loss {min_val_loss:.6f} @ epoch{best_epoch}")

    # Log best checkpoint to W&B as a versioned artifact.
    if wandb_run is not None and config.get("wandb_log_ckpts", False):
        try:
            artifact = wandb.Artifact(f"{config['task_name']}_policy_best", type="model")
            artifact.add_file(ckpt_path)
            wandb_run.log_artifact(artifact, aliases=["best"])
        except Exception as exc:
            print(f"[W&B] Failed to log best checkpoint artifact. Error: {exc}")

    if wandb_run is not None:
        wandb_run.finish()


def make_policy(policy_class, policy_config):
    if policy_class == "ACT":
        policy = ACTPolicy(policy_config)
    elif policy_class == "CNNMLP":
        policy = CNNMLPPolicy(policy_config)
    else:
        raise NotImplementedError
    return policy


def make_optimizer(policy_class, policy):
    if policy_class == "ACT":
        optimizer = policy.configure_optimizers()
    elif policy_class == "CNNMLP":
        optimizer = policy.configure_optimizers()
    else:
        raise NotImplementedError
    return optimizer


def forward_pass(data, policy):
    cam_data, tac_data, qpos_data, action_data, is_pad = data
    cam_data, tac_data, qpos_data, action_data, is_pad = (
        cam_data.cuda(),
        tac_data.cuda(),
        qpos_data.cuda(),
        action_data.cuda(),
        is_pad.cuda(),
    )
    return policy(qpos_data, cam_data, tac_data, action_data, is_pad)  # TODO remove None


def train_bc(train_dataloader, val_dataloader, config):
    ckpt_dir = config["ckpt_dir"]
    seed = config["seed"]
    policy_class = config["policy_class"]
    policy_config = config["policy_config"]

    set_seed(seed)

    policy = make_policy(policy_class, policy_config)
    policy.cuda()
    optimizer = make_optimizer(policy_class, policy)

    train_history = []
    validation_history = []
    min_val_loss = np.inf
    best_ckpt_info = None

    step_count = 0
    num_steps = config['num_steps']
    epoch = 0
    
    pbar = tqdm(range(num_steps), total=num_steps, leave=False)
    while True:
        policy.train()
        optimizer.zero_grad()
        for batch_idx, data in enumerate(train_dataloader):
            forward_dict = forward_pass(data, policy)
            # backward
            loss = forward_dict["loss"]
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            train_history.append(detach_dict(forward_dict))

            pbar.set_postfix({'epoch': epoch, 'loss': loss.item()})
            pbar.update(1)

            step_count += 1
            if step_count > num_steps:
                break

            if step_count % config['save_freq'] == 0:
                ckpt_path = os.path.join(ckpt_dir, f"policy_epoch_{epoch + 1}_seed_{seed}.ckpt")
                torch.save(policy.state_dict(), ckpt_path)
                plot_history(train_history, validation_history, epoch, ckpt_dir, seed)

                # Optional: upload intermediate checkpoints.
                if wandb is not None and wandb.run is not None and config.get("wandb_log_ckpts", False):
                    try:
                        artifact = wandb.Artifact(
                            f"{config['task_name']}_policy_epoch_{epoch + 1}",
                            type="model",
                        )
                        artifact.add_file(ckpt_path)
                        wandb.run.log_artifact(artifact)
                    except Exception as exc:
                        print(f"[W&B] Failed to log intermediate checkpoint artifact. Error: {exc}")

            # Log train losses per step (cheap scalar logging).
            if wandb is not None and wandb.run is not None:
                try:
                    def _scalar(x):
                        # forward_dict values are typically 0-d tensors
                        return float(x.item()) if hasattr(x, "item") else float(x)

                    to_log = {f"train/{k}": _scalar(v) for k, v in forward_dict.items() if k != "loss"}
                    to_log["train/loss"] = _scalar(forward_dict["loss"])
                    to_log["train/epoch"] = float(epoch)
                    to_log["train/step"] = float(step_count)
                    wandb.log(to_log, step=step_count)
                except Exception:
                    pass

        epoch_summary = compute_dict_mean(train_history[(batch_idx + 1) * epoch:(batch_idx + 1) * (epoch + 1)])
        epoch_train_loss = epoch_summary["loss"]

        train_summary_string = ""
        for k, v in epoch_summary.items():
            train_summary_string += f"{k}: {v.item():.3f} "

        with torch.inference_mode():
            policy.eval()
            epoch_dicts = []
            for batch_idx, data in enumerate(val_dataloader):
                forward_dict = forward_pass(data, policy)
                epoch_dicts.append(forward_dict)

            epoch_summary = compute_dict_mean(epoch_dicts)
            validation_history.append(epoch_summary)

            epoch_val_loss = epoch_summary["loss"]
            if epoch_val_loss < min_val_loss:
                min_val_loss = epoch_val_loss
                best_ckpt_info = (epoch, min_val_loss, deepcopy(policy.state_dict()))

            # Log validation losses per epoch.
            if wandb is not None and wandb.run is not None:
                try:
                    val_to_log = {f"val/{k}": float(v.item() if hasattr(v, "item") else v) for k, v in epoch_summary.items()}
                    val_to_log["val/epoch"] = float(epoch)
                    val_to_log["val/best"] = bool(epoch_val_loss == min_val_loss)
                    wandb.log(val_to_log, step=step_count)
                except Exception:
                    pass

        eval_summary_string = ""
        for k, v in epoch_summary.items():
            eval_summary_string += f"{k}: {v.item():.3f} "

        if step_count > num_steps:
            break
        epoch += 1

    ckpt_path = os.path.join(ckpt_dir, f"policy_last.ckpt")
    torch.save(policy.state_dict(), ckpt_path)

    # Optional: upload last checkpoint as artifact.
    if wandb is not None and wandb.run is not None and config.get("wandb_log_ckpts", False):
        try:
            artifact = wandb.Artifact(f"{config['task_name']}_policy_last", type="model")
            artifact.add_file(ckpt_path)
            wandb.run.log_artifact(artifact, aliases=["last"])
        except Exception as exc:
            print(f"[W&B] Failed to log last checkpoint artifact. Error: {exc}")

    best_epoch, min_val_loss, best_state_dict = best_ckpt_info
    ckpt_path = os.path.join(ckpt_dir, f"policy_epoch_{best_epoch}_seed_{seed}.ckpt")
    torch.save(best_state_dict, ckpt_path)
    print(f"Training finished:\nSeed {seed}, val loss {min_val_loss:.6f} at epoch {best_epoch}")

    # save training curves
    plot_history(train_history, validation_history, epoch, ckpt_dir, seed)

    return best_ckpt_info


def plot_history(train_history, validation_history, num_epochs, ckpt_dir, seed):
    # save training curves
    for key in train_history[0]:
        plot_path = os.path.join(ckpt_dir, f"train_val_{key}_seed_{seed}.png")
        plt.figure()
        train_values = [summary[key].item() for summary in train_history]
        val_values = [summary[key].item() for summary in validation_history]
        plt.plot(
            np.linspace(0, num_epochs - 1, len(train_history)),
            train_values,
            label="train",
        )
        plt.plot(
            np.linspace(0, num_epochs - 1, len(validation_history)),
            val_values,
            label="validation",
        )
        # plt.ylim([-0.1, 1])
        plt.tight_layout()
        plt.legend()
        plt.title(key)
        plt.savefig(plot_path)
    print(f"Saved plots to {ckpt_dir}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--eval", action="store_true")
    parser.add_argument("--onscreen_render", action="store_true")
    parser.add_argument("--ckpt_dir", action="store", type=str, help="ckpt_dir", required=True)
    parser.add_argument("--task_name", action="store", type=str, help="task_name", required=True)
    parser.add_argument("--config_path", action="store", type=str, help="config_path", required=True)
    parser.add_argument("--seed", action="store", type=int, help="seed", required=True)

    # Make training parameters optional so they can be loaded from YAML
    parser.add_argument("--policy_class", type=str, required=False)
    parser.add_argument("--num_epochs", type=int, required=False)
    parser.add_argument("--state_dim", type=int, required=False)
    parser.add_argument("--lr", type=float, required=False)
    parser.add_argument("--batch_size", type=int, required=False)
    parser.add_argument("--num_steps", type=int, required=False)
    parser.add_argument("--save_freq", type=int, required=False)

    # W&B defaults (can be disabled by setting WANDB_DISABLED=1).
    parser.add_argument("--wandb_project", type=str, required=False, default="UniVTAC")
    parser.add_argument("--wandb_entity", type=str, required=False, default=None)
    parser.add_argument("--wandb_mode", type=str, required=False, default="online")
    parser.add_argument("--wandb_run_name", type=str, required=False, default=None)
    ckpt_group = parser.add_mutually_exclusive_group()
    ckpt_group.add_argument("--wandb_log_ckpts", dest="wandb_log_ckpts", action="store_true")
    ckpt_group.add_argument("--no_wandb_log_ckpts", dest="wandb_log_ckpts", action="store_false")
    parser.set_defaults(wandb_log_ckpts=True)


    args = parser.parse_args()
    with open(args.config_path, 'r') as f:
        config_args = yaml.load(f, Loader=yaml.FullLoader)
    
    # Merge CLI args into YAML config, but only if they were actually provided
    for k, v in vars(args).items():
        if v is not None:
            config_args[k] = v
    
    main(config_args)
